### ISSUE TITLE
Deprecated packages - 015-apt-gnome

### ISSUE THREAD

**Issue by Jaczel** [MomsFriendlyDevCo/Init#2]
* `gnome-netstatus-applet` has been deprecated and can maybe be replaced by `nagstamon` or `netmonitor`

* `gnome-art` has been deprecated

* `nautilus-open-terminal` has been deprecated

* `gnome-themes-extras` has been deprecated, can be replaced by `gnome-themes-standard` and gnome-themes-ubuntu`

* `timer-applet` replaced by `alarm-clock-applet`

**Comment by hash-bang** [comment]
Thanks for correcting these.
