### ISSUE TITLE
Provided monit confs have been moved to /etc/monit/conf-available

### ISSUE THREAD

**Issue by Jaczel** [MomsFriendlyDevCo/Init#5]
The following lines are incorrect as the location of these files have been moved to `/etc/monit/conf-available/`:

`echo 'include /etc/monit/monitrc.d/mysql' | sudo tee -a '/etc/monit/monitrc'`
`echo 'include /etc/monit/monitrc.d/apache2' | sudo tee -a '/etc/monit/monitrc'`
`echo 'include /etc/monit/monitrc.d/postfix' | sudo tee -a '/etc/monit/monitrc'`

Lines should now read:
`echo 'include /etc/monit/conf-available/mysql' | sudo tee -a '/etc/monit/monitrc'`
`echo 'include /etc/monit/conf-available/apache2' | sudo tee -a '/etc/monit/monitrc'`
`echo 'include /etc/monit/conf-available/postfix' | sudo tee -a '/etc/monit/monitrc'`

This new location is reflected in the Ansible `monit` role setup.

**Comment by hash-bang** [comment]
No problem.
